# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e9bc0e4fb21c430015a5fd7837b71af0c5aa81584c1b160b9397f7245ba500b5baa3ea2dade130c5e9a69e1835856ae83be8acc851e2fa2fe87432c16c0008

test:
  secret_key_base: bd05f2e4146ee555c5e5ffa8594f7cd341a9ff365ee647e1a09eacb81f0b9a0ea1efc4b17dfec3476dfd8f789d57cd5617063adab8f0738999bb74d011f0cb0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
